server.port=1664

kafka.producer.TOPIC.NAME=ms-orders-distributor
kafka.producer.CLIENT_ID_CONFIG=ms-orders-distributor-p
kafka.common.BOOTSTRAP_SERVERS_CONFIG=localhost:9092

#Default Configuration
kafka.producer.LINGER_MS_CONFIG=10
kafka.producer.BATCH_SIZE_CONFIG=64000
kafka.producer.COMPRESSION_TYPE_CONFIG=snappy
fetch.max.size.limit=10000

spring.main.allow-bean-definition-overriding=true

#Azure blob storage
azure.storage.connection.string=YOUR_AZURE_STORAGE_CONNECTION_STRING
azure.storage.container.name=order-kafka

spring.http.multipart.max-file-size=10MB
spring.http.multipart.max-request-size=11MB
one.pharma.send.email=
order.failed.notification.email.recipients=
egCloud.order.status.update.url.endpoint=https://c2-api-qa.ril.com/live/update-web-order-status

#getSellerLogo
seller.logo.url= http://localhost:2260/c2/lc/na/seller/logo

#getUitem
seller.uitem.url= http://localhost:2260/c2/lc/na/seller/uitem

#OrderSync
order.lo.lc = http://localhost:2260/c2/lc/na/loToLc