#spring.datasource.url=jdbc:mysql://liveconnectbackup24072019-cluster.cluster-ro-chjsglnbt4kn.ap-south-1.rds.amazonaws.com:3306/order_buk_new
#spring.datasource.url=jdbc:mysql://ob-aurora-singleaz-master-cluster.cluster-chjsglnbt4kn.ap-south-1.rds.amazonaws.com:3306/order_buk_new
#spring.datasource.username=obuk
#spring.datasource.password=Orderbuk@12

postgres.jpa.database=POSTGRESQL
postgres.datasource.platform=postgres
postgres.datasource.driverClassName=com.p6spy.engine.spy.P6SpyDriver
postgres.datasource.url=jdbc:p6spy:postgresql://10.20.1.4:5432/ms_order
postgres.datasource.username=postgres
postgres.datasource.password=ZZ3g3REChYYbNbz6
postgres.jpa.hibernate.ddl-auto=validate
postgres.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


postgres.datasource.hikari.poolName=SpringBootJPAHikariCP
postgres.datasource.hikari.connectionTimeout=300000
postgres.datasource.hikari.idleTimeout=200000
postgres.datasource.hikari.maxLifetime=250000
postgres.datasource.hikari.maximumPoolSize=5
postgres.datasource.hikari.minimumIdle=2

#spring.jpa.hibernate.ddl-auto=validate
hibernate.jdbc.lob.non_contextual_creation=true
postgres.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
mysql.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

#mongo config
spring.data.mongodb.host = 10.20.1.4
spring.data.mongodb.port = 27017
spring.data.mongodb.database = ms_order
spring.data.mongodb.username = devadmin
spring.data.mongodb.password = SDXxXQFdkExkFq8j
spring.data.mongodb.authentication-database = admin

spring.data.mongodb.keepAlive=true
spring.data.mongodb.poolSize=5
spring.data.mongodb.autoReconnect=true
spring.data.mongodb.socketTimeoutMS=120000
spring.data.mongodb.connectTimeoutMS=12000

#mysql
mysql.datasource.url =jdbc:p6spy:mysql://qa-liveconnect.mysql.database.azure.com/order_buk_new?serverTimezone=UTC
mysql.datasource.username =obuk@qa-liveconnect
mysql.datasource.password =Orderbuklc123

mysql.datasource.hikari.poolName=SpringBootJPAHikariCPMysql
mysql.datasource.hikari.connectionTimeout=300000
mysql.datasource.hikari.idleTimeout=350000
mysql.datasource.hikari.maxLifetime=450000
mysql.datasource.hikari.maximumPoolSize=5
mysql.datasource.hikari.minimumIdle=2

